services:
  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: Gateway.API/Dockerfile
    ports:
    - "5000:5000"
    - "5001:5001"
    networks:
    - clusterbackend

  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: Users.API/Dockerfile
    ports:
    - "5100:5100"
    - "5101:5101"
    networks:
    - clusterbackend

networks:
  clusterbackend:
    name: clusterbackend
    driver: bridge
