apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-script
data:
  auth-load-test.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export let options = {
      stages: [
        { duration: '30s', target: 10 },
        { duration: '1m', target: 50 },
        { duration: '30s', target: 0 },
      ],
    };

    export default function () {
      const res = http.get('http://auth/health');
      check(res, {
        'status is 200': (r) => r.status === 200,
      });
      sleep(1);
    }
